import { Whisky } from './types';

export const WHISKY_DATA: Whisky[] = [
  {
    id: 'w1',
    name: 'Lagavulin 16',
    distillery: 'Lagavulin',
    region: 'Islay',
    country: 'Scotland',
    type: 'Single Malt',
    abv: 43,
    age: 16,
    priceRange: '£75-£90',
    description: 'A classic Islay malt, known for its intense peat smoke and rich sweetness. A staple of the Draycott Drams collection.',
    tastingNotes: ['Lapsang Souchong smoke', 'Dried fruit', 'Vanilla', 'Malty sweetness'],
    coordinates: [-6.126, 55.636],
    flavorProfile: { peat: 95, fruit: 40, floral: 10, spice: 50, wood: 70, sweetness: 50 }
  },
  {
    id: 'w2',
    name: 'Yamazaki 12',
    distillery: 'Yamazaki',
    region: 'Osaka',
    country: 'Japan',
    type: 'Single Malt',
    abv: 43,
    age: 12,
    priceRange: '£150+',
    description: 'Japan’s premier single malt. Complex, spicy, and fruity, matured in three different types of oak casks.',
    tastingNotes: ['Peach', 'Candied orange', 'Cinnamon', 'Clove'],
    coordinates: [135.674, 34.891],
    flavorProfile: { peat: 10, fruit: 80, floral: 60, spice: 70, wood: 60, sweetness: 60 }
  },
  {
    id: 'w3',
    name: 'Redbreast 12',
    distillery: 'Midleton',
    region: 'Cork',
    country: 'Ireland',
    type: 'Single Pot Still',
    abv: 40,
    age: 12,
    priceRange: '£50-£60',
    description: 'A masterpiece of Irish whiskey. Full-flavored and complex; a harmonious balance of spicy, creamy, fruity, sherry and toasted notes.',
    tastingNotes: ['Spicy fruit', 'Toasted wood', 'Sherry', 'Creamy texture'],
    coordinates: [-8.172, 51.913],
    flavorProfile: { peat: 0, fruit: 75, floral: 30, spice: 80, wood: 50, sweetness: 70 }
  },
  {
    id: 'w4',
    name: 'Balvenie DoubleWood 12',
    distillery: 'Balvenie',
    region: 'Speyside',
    country: 'Scotland',
    type: 'Single Malt',
    abv: 40,
    age: 12,
    priceRange: '£45-£55',
    description: 'Matured in two distinct casks: traditional oak and European oak sherry casks. Smooth and mellow.',
    tastingNotes: ['Honey', 'Vanilla', 'Sherry', 'Cinnamon'],
    coordinates: [-3.125, 57.447],
    flavorProfile: { peat: 5, fruit: 60, floral: 40, spice: 40, wood: 60, sweetness: 80 }
  },
  {
    id: 'w5',
    name: 'Buffalo Trace',
    distillery: 'Buffalo Trace',
    region: 'Kentucky',
    country: 'USA',
    type: 'Bourbon',
    abv: 45,
    priceRange: '£25-£35',
    description: 'A deep amber bourbon with a complex aroma of vanilla, mint, and molasses. Pleasantly sweet to the taste.',
    tastingNotes: ['Brown sugar', 'Toffee', 'Oak', 'Dark fruit'],
    coordinates: [-84.871, 38.214],
    flavorProfile: { peat: 0, fruit: 30, floral: 10, spice: 50, wood: 90, sweetness: 85 }
  },
  {
    id: 'w6',
    name: 'Talisker 10',
    distillery: 'Talisker',
    region: 'Isle of Skye',
    country: 'Scotland',
    type: 'Single Malt',
    abv: 45.8,
    age: 10,
    priceRange: '£40-£50',
    description: 'A powerful, spicy, sea-salty character. The only distillery on the Isle of Skye.',
    tastingNotes: ['Sea salt', 'Bonfire smoke', 'Black pepper', 'Barley'],
    coordinates: [-6.357, 57.302],
    flavorProfile: { peat: 70, fruit: 30, floral: 15, spice: 85, wood: 40, sweetness: 30 }
  },
  {
    id: 'w7',
    name: 'Kavalan Concertmaster',
    distillery: 'Kavalan',
    region: 'Yilan',
    country: 'Taiwan',
    type: 'Single Malt',
    abv: 40,
    priceRange: '£55-£70',
    description: 'Finished in Port barriques. A rich, full-bodied whisky with distinct tropical fruit notes from the Taiwanese climate.',
    tastingNotes: ['Tropical fruit', 'Chocolate', 'Berry jam', 'Coconut'],
    coordinates: [121.708, 24.717],
    flavorProfile: { peat: 0, fruit: 90, floral: 50, spice: 30, wood: 40, sweetness: 80 }
  },
  {
    id: 'w8',
    name: 'Amrut Fusion',
    distillery: 'Amrut',
    region: 'Bangalore',
    country: 'India',
    type: 'Single Malt',
    abv: 50,
    priceRange: '£50-£65',
    description: 'A fusion of Indian and Scottish barley. Highly rated and robust, proving Indian whisky on the global stage.',
    tastingNotes: ['Coffee', 'Dark chocolate', 'Oak', 'Gentle peat'],
    coordinates: [77.537, 12.876],
    flavorProfile: { peat: 20, fruit: 50, floral: 10, spice: 80, wood: 60, sweetness: 40 }
  }
];
